<?php

namespace AppBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUpcomingMovies($resultsNumber = 50)
    {
        //version dql
        $dql = "SELECT e
                FROM AppBundle:Movie e
                WHERE e.year >= :now
                ORDER BY e.year";

        $query = $this->getEntityManager()->createQuery($dql);

        $query->setParameters(["now" => new \DateTime()]);

        $query->setMaxResults($resultsNumber);
        $movies = $query->getResult();

        dump($movies);

        return $movies;
    }

}
