app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Movie:index }

movie_detail:
    path:     /movies/{id}/details
    defaults: { _controller: AppBundle:Movie:detail }
    requirements:
          id: '\d+'

admin_movie_create:
    path:     /admin/movie_create
    defaults: { _controller: AppBundle:AdminMovie:create }

admin_movie_edit:
    path:     /admin/{id}/movie_edit
    defaults: { _controller: AppBundle:AdminMovie:edit }
    requirements:
              id: '\d+'

admin_movie_delete:
    path:     /admin/{id}/movie_delete
    defaults: { _controller: AppBundle:AdminMovie:delete }
    requirements:
              id: '\d+'

admin_movie_list:
    path:     /admin/movie_list
    defaults: { _controller: AppBundle:AdminMovie:list }

admin_review_edit:
    path:     /admin/{id}/review_edit
    defaults: { _controller: AppBundle:AdminReview:edit }
    requirements:
              id: '\d+'

admin_review_delete:
    path:     /admin/{id}/review_delete
    defaults: { _controller: AppBundle:AdminReview:delete }
    requirements:
              id: '\d+'

admin_review_list:
    path:     /admin/review_list
    defaults: { _controller: AppBundle:AdminReview:list }
