app_homepage:
    path:     /{page}
    defaults: { _controller: AppBundle:Movie:index, page: 1 }
    requirements:
            page: '\d+'

movie_detail:
    path:     /movies/{id}/details
    defaults: { _controller: AppBundle:Movie:detail }
    requirements:
          id: '\d+'

admin_movie_create:
    path:     /admin/movie_create
    defaults: { _controller: AppBundle:AdminMovie:create }

admin_movie_edit:
    path:     /admin/{id}/movie_edit
    defaults: { _controller: AppBundle:AdminMovie:edit }
    requirements:
              id: '\d+'

admin_movie_delete:
    path:     /admin/{id}/movie_delete
    defaults: { _controller: AppBundle:AdminMovie:delete }
    requirements:
              id: '\d+'

admin_movie_list:
    path:     /admin/movie_list
    defaults: { _controller: AppBundle:AdminMovie:list }

admin_review_edit:
    path:     /admin/{id}/review_edit
    defaults: { _controller: AppBundle:AdminReview:edit }
    requirements:
              id: '\d+'

admin_review_delete:
    path:     /admin/{id}/review_delete
    defaults: { _controller: AppBundle:AdminReview:delete }
    requirements:
              id: '\d+'

admin_review_list:
    path:     /admin/review_list
    defaults: { _controller: AppBundle:AdminReview:list }

user_register:
    path:     /utilisateurs/inscription/
    defaults: { _controller: AppBundle:User:register }

login:
    path:     /connexion/
    defaults: { _controller: AppBundle:User:login }

#c'est symfony qui se charge des déconnexion donc on ne met pas de methode
logout:
    path:     /deconnexion/